Bloggie.Web/Controllers/AdminBlogPostsController.cs
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bloggie.Web.Models.Domain;
using Microsoft.AspNetCore.Authorization;

namespace Bloggie.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostsController : Controller
	{
		private readonly ITagRepository tagRepository;
		private readonly IBlogPostRepository blogPostRepository;

		// Constructor with dependencies injection (Tag repo and BP repo)
		public AdminBlogPostsController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
			this.tagRepository = tagRepository;
			this.blogPostRepository = blogPostRepository;
		}
        
        [HttpGet]
		public async Task<IActionResult> Add()
		{
			// get tags from repository
			var tags = await tagRepository.GetAllTagsAsync();
			var model = new AddBlogPostRequest
			{
				Tags = tags.Select(tag => new SelectListItem { Text = tag.Name, Value = tag.Id.ToString() })
			};

			return View(model);
		}

        [HttpPost]
		public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
		{
			// Map view model to domain model
			var blogPost = new BlogPost
			{
				Heading = addBlogPostRequest.Heading,
				PageTitle = addBlogPostRequest.PageTitle,
				Content = addBlogPostRequest.Content,
				ShortDescription = addBlogPostRequest.ShortDescription,
				FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
				UrlHandle = addBlogPostRequest.UrlHandle,
				PublishedDate = addBlogPostRequest.PublishedDate,
				Author = addBlogPostRequest.Author,
				Visible = addBlogPostRequest.Visible
			};

			// Map tags from selected tags
			var selectedTags = new List<Tag>();
			foreach (var selectedTagId in addBlogPostRequest.SelectedTags) 
			{
				var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
				var existingTag = await tagRepository.GetTagAsync(selectedTagIdAsGuid);

				if (existingTag != null) 
				{
					selectedTags.Add(existingTag);
				}
			}

			// Mapping tags back to domain model
			blogPost.Tags = selectedTags;

			await blogPostRepository.AddBlogPostAsync(blogPost);

			return RedirectToAction("Add");
		}

        [HttpGet]
		public async Task<IActionResult> List()
		{
			// Call the repository
			var blogPosts = await blogPostRepository.GetAllPostsAsync();

			return View(blogPosts); 
		}

        [HttpGet]
		public async Task<IActionResult> Edit(Guid id)
		{
			// Retrieve the result from the repository
			var blogPost = await blogPostRepository.GetBlogPostAsync(id);
			var tagsDomainModel = await tagRepository.GetAllTagsAsync();

			if (blogPost != null)
			{
				// map domain model into view model
				var model = new EditBlogPostRequest
				{
					Id = blogPost.Id,
					Heading = blogPost.Heading,
					PageTitle = blogPost.PageTitle,
					Content = blogPost.Content,
					Author = blogPost.Author,
					FeaturedImageUrl = blogPost.FeaturedImageUrl,
					UrlHandle = blogPost.UrlHandle,
					ShortDescription = blogPost.ShortDescription,
					PublishedDate = blogPost.PublishedDate,
					Visible = blogPost.Visible,
					Tags = tagsDomainModel.Select(tag => new SelectListItem { Text = tag.Name, Value = tag.Id.ToString() }),
					SelectedTags = blogPost.Tags.Select(tag => tag.Id.ToString()).ToArray()
				};
				// Pass data to view
				return View(model);
			}

			return View(null);
		}

        [HttpPost]
		public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
		{
			// map view model back to domain model
			var blogPostDomainModel = new BlogPost
			{
				Id = editBlogPostRequest.Id,
				Heading = editBlogPostRequest.Heading,
				PageTitle = editBlogPostRequest.PageTitle,
				Content = editBlogPostRequest.Content,
				Author = editBlogPostRequest.Author,
				FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
				UrlHandle = editBlogPostRequest.UrlHandle,
				ShortDescription = editBlogPostRequest.ShortDescription,
				PublishedDate = editBlogPostRequest.PublishedDate,
				Visible = editBlogPostRequest.Visible
			};

			// map tags into domain model
			var selectedTags = new List<Tag>();
			foreach(var selectedTag in editBlogPostRequest.SelectedTags)
			{
				if(Guid.TryParse(selectedTag, out var tag))
				{
					var foundTag = await tagRepository.GetTagAsync(tag);
					if (foundTag != null)
					{
						selectedTags.Add(foundTag); 
					}
				}
			}

			blogPostDomainModel.Tags = selectedTags;

			// submit information to repository to update
			var updatedBlogPost = await blogPostRepository.UpdateBlogPostAsync(blogPostDomainModel);

			if (updatedBlogPost != null) 
			{
				// Show success notification
				return RedirectToAction("List");
			}

			// Show error notification
			return RedirectToAction("Edit");
		}

        [HttpPost]
		public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
		{
			// Talk to repo to delete this blogpost and tags
			var deletedBlogPost = await blogPostRepository.DeleteBlogPostAsync(editBlogPostRequest.Id);

			// Display response
			if (deletedBlogPost != null) 
			{
				// show success notification
				return RedirectToAction("List");
			}
			else
			{
				// show error notification
				return RedirectToAction("Edit", new { id = editBlogPostRequest.Id });
			}
		}
	}
}

Bloggie.Web/Controllers/AdminTagsController.cs
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bloggie.Web.Controllers
{
    // if logged in as an Admin gives way to the user to operate CRUD operations on tags
    [Authorize(Roles = "Admin")]
    public class AdminTagsController : Controller
    {
        // injected repository class usable in this class
		private readonly ITagRepository tagRepository;

        // Constructor used to inject 
		public AdminTagsController(ITagRepository tagRepository)
        {
            // injecting the repository class
			this.tagRepository = tagRepository;
		}

        // Retrieves datas from the database about the Add Tag Page
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        // Used to operate the Add operation on the database from the Add Tag Page (functionality)
        [HttpPost]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            ValidateAddTagRequest(addTagRequest);

            if (ModelState.IsValid) 
            {
                // Mapping the addTagRequest to Tag domain model
                var tag = new Tag
                {
                    Name = addTagRequest.Name,
                    DisplayName = addTagRequest.DisplayName
                };

                await tagRepository.AddTagAsync(tag);

                return RedirectToAction("List");
            }

            return View();
        }

        // Controls on the datas before to send those to the DB, if fails the request gets invalidated
		private void ValidateAddTagRequest(AddTagRequest request)
		{
			if (request.Name != null && request.DisplayName != null)
            {
                if (request.DisplayName == request.Name)
                {
                    ModelState.AddModelError("DisplayName", "Name cannot be the same as DisplayName");
                } 
            }
		}

		// Retrieves datas from the database about all the tags in the correct format (search functionality, sorting, pagination)
		[HttpGet]
        public async Task<IActionResult> List(string? searchQuery, 
                                              string? sortBy, 
                                              string? sortDirection,
                                              int pageSize = 3,
                                              int pageNumber = 1)
        {
            var totalRecords = await tagRepository.CountAsync();
            var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

            if (pageNumber > totalPages)
            {
                pageNumber--;
            }

            if (pageNumber < 1)
            {
                pageNumber++;
            }

			ViewBag.TotalPages = totalPages;
			ViewBag.SearchQuery = searchQuery;
			ViewBag.SortBy = sortBy;
			ViewBag.SortDirection = sortDirection;
            ViewBag.PageSize = pageSize;
            ViewBag.PageNumber = pageNumber;
            
			// Use DbContext to read the tags
			var tags = await tagRepository.GetAllTagsAsync(searchQuery, sortBy, sortDirection, pageNumber, pageSize);
            
            return View(tags);
        }

        // Retrieves datas from the DB about the selected tag 
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            // 1st method
            //var tag = bloggieDbContext.Tags.Find(id);

            var tag = await tagRepository.GetTagAsync(id);

            if (tag != null) 
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };

				return View(editTagRequest);
			}

            return View(null);
        }

		// Exposes a way to the user for updating the selected Tag
		[HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

            var updatedTag = await tagRepository.UpdateTagAsync(tag);

            if (updatedTag != null) 
            {
                // Show success notification
            }
            else
            {
				// Show error notification
			}

            return RedirectToAction("List");
			//return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }

		// Exposes a way to the user for deleting the selected Tag
		[HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
            var deletedTag = await tagRepository.DeleteTagAsync(editTagRequest.Id);

            if (deletedTag != null) 
            {
                // Show success notification
                return RedirectToAction("List");
			}

			// Show error notification
			return RedirectToAction("Edit", new { id = editTagRequest.Id });
		}
    }
}

Bloggie.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bloggie.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bloggie.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <!-- FROALA -->
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">

                <!-- Title of the website -->
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LOGS</a>

                <!-- Navbar buttons toggler for smartphones -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- NavBar options -->
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <!--Home button -->
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <!-- Admin dropdown if logged in as Admin -->
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item"
                                           asp-area=""
                                           asp-controller="AdminTags"
                                           asp-action="Add">
                                            Add Tag
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           asp-area=""
                                           asp-controller="AdminTags"
                                           asp-action="List">
                                            Show All Tags
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           asp-area=""
                                           asp-controller="AdminBlogPosts"
                                           asp-action="Add">
                                            Add Blog Post
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           asp-area=""
                                           asp-controller="AdminBlogPosts"
                                           asp-action="List">
                                            Show Posts
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           asp-area=""
                                           asp-controller="AdminUsers"
                                           asp-action="List">
                                            Show Users
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }

                    </ul>

                    <!-- Login / Register / Logout BUTTONS -->
                    <div class="d-flex align-items-center">

                        <!-- LOGIN/REGISTER/LOGOUT BUTTONS -->
                        @if (signInManager.IsSignedIn(User))
                        {
                            <div class="me-3 text-light">
                                @User?.Identity?.Name
                            </div>

                            <a class=" btn me-3 bg-light text-dark"
                               asp-area=""
                               asp-controller="Account"
                               asp-action="Logout">Logout</a>
                        }
                        else
                        {
                            <a class=" btn me-3 bg-light text-dark"
                               asp-area=""
                               asp-controller="Account"
                               asp-action="Login">Login</a>

                            <a class=" btn me-3 bg-light text-dark"
                               asp-area=""
                               asp-controller="Account"
                               asp-action="Register">Register</a>
                        }

                    </div>
                </div>
            </div>
        </nav>
    </header>

    <!-- Render the body of the view -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <!-- Footer -->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Bloggie.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>